### PR TITLE
Implement Custom Component to render CDX Summary JSON

### PR DESCRIPTION
**Pull request by ibnesayeed**
This Custom Component has special code to support summary of the Internet Archive's Petabox Items/Collections with WARC files.

### CODE REVIEW

**Comment by vbanos** [comment]
If we run this component under `archive.org` or `web.archive.org`, consider that Bootstrap 3 will be already loaded.
You could use it to improve the looks of the app and make it consistent with the rest of the WBM UI.

**Comment by vbanos** [comment]
The URLs in "100 Random Samples of OK HTML Mementos" could be very very long. (I mean, thousands of chars).
Even in your example, you have a few very long ones like:

https://www.facebook.com/ajax/bz?__a=1&__beoa=0&__ccg=EXCELLENT&__comet_req=0&__csr=&__dyn=7AgNe5Gmawgrolg9odpbGEnxd4Wo5OdwJCxucxu13wqohzkdxK5WwAyUG4XzE4q15zobohx3wCgdoO2S1ixi3y4o4O1twWG7Elw86l0DwLwxwAxCWwSxu15wgE46fwiu3e6ogxOfwwwn8-8BxG10guy846mfzUO9Bwu85q6E4a488rAy8aEaoG1HwOwnolwBgK4oKEtwi8b82kwnGwWwlo8od8-7EbFo5e4Ueo2swkEbElxm3y1lxu16wbG&__hsi=6907890306140338971-0&__pc=PHASED%3ADEFAULT&__req=1jw&__rev=1003133429&__s=mponxe%3Aybu1wt%3Ar5m024&__spin_b=trunk&__spin_r=1003133429&__spin_t=1608368546&__user=0&dpr=1&jazoest=21039&lsd=AVp4iXexlWs
 
IMHO its not nice for the UI to have URLs that are multiple lines long.
You could use JS or CSS to display the first N chars only and put "..." in the end.

**Comment by ibnesayeed** [comment]
Thanks @vbanos for this info. I am not sure if have any immediate plans to use it on `web.archive.org`, but that might change in the future.

For now, this is intended to be used under `archive.org/details/`. By rendering it under a Shadow DOM, we are actually isolating it from the style scope of the page, so there is not a lot we can leverage from the host page. That said, we can provide a handful of style variables to allow customization for consistency.

**Comment by ibnesayeed** [comment]
> IMHO its not nice for the UI to have URLs that are multiple lines long.
> You could use JS or CSS to display the first N chars only and put "..." in the end.

I actually experimented with applying some CSS for overflow ellipsis behavior earlier, but being able to look at the full URI seemed more important for the realization and inspection of what is being archived. On narrow screens and on pages where a sidebar is also included, a lot of useful information would be hidden. So, I reverted that style.

That said, not only the length of URIs, but we also need to prevent some malformed URIs (e.g., those showing alerts) from getting injected on the page. I was thinking about excluding URIs from the sample in the first place that do not meet certain niceness criteria (e.g., too long, too many query parameters, repeated sequences, encoded JS, etc.). For now, only three things are checked for inclusion.

https://github.com/internetarchive/cdx-summary/blob/f502e02f0c9647c3c92fa191a71335b93b835dc2/cdxsummary/analyzer.py#L17-L18

**Comment by ibnesayeed** [comment]
@vbanos I have removed `https?://` and `www.` prefixes from sample URIs and sorted them by their lengths. Now, the list does not look as cluttered.

**Pull request merged**
